apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCT82fds8djET3ZBanmL5YH2kQFFyp9RzKwwS5xguHNoAJ+6COqTZjomae/eH3+aPu7rpiPT/43C00BdF6IZjx52I/NIHwC0HKofrdDedOzJ3xWb1eXUNXaHDNMGwlDsKfdW21JLq86AkEPPdVtfs20Qudnk4ChsZjCdxLCfJ4xZrA/JDJz2cMlJI8ad1Hwr6dFe9Wt5ikBCilfR/8DEvM0CtRwBVjT1F1KTmaCfs9PtVsQkLNNWQObXYvpF26ayKmu5sjwsQ9bS2dIuE7qBRQZ1/0fsOCeQNCwtyR5FeVbWOG9MBvAMFijiDd7QdqpS1VN3tEJebKvS2S30U3x7a0OoXEpMuCy8+3TPSHYBTbFtA9QJ2w81XGL8lGHmjrjqLXWMRLMFNIbUWOAtIDLi76SgWsY7qkJsfnvbNWo8ItTXcFBhYgHf8wPxRUsVIV00/yaVQfefs1gjUJhni8+wJLOau3LSrZE4gKnKnFS61U/B3zhlIDzQGQW1U3K6I4jx2x8KiIN0nJXkc74Y3vINwTLzo5nO52gWyfJG2oS3yoFQLS/3/RdT/QqScflhakV6Q6TZ7v7ni8Zz3LfQWouJMFauodfYnLjXwGn7HLCJJSymkQBVXcttOoPWZUwvX4oStYSKCcDYHXptIlRPwjpGNxRYN8ryqAHvoXbIuum2LNK4o8MCjhMm5NoH/wrOA1bBzSw/z8w4OhN7lSOliTZhw==
    database-password: AgBYiLqohQGHiP4XNrpWSBtbCHN+q9vFzKu9P4VKM8LdVCX4QRaSaAnCJND0y+1f0+4ZTmoKxt3gHHCWS1zo3vFYOvrdJjR5LpxT7wsAeXKOVz227Z6fjhoP2pDs8bF+fHD6QEJ4qWmhOuflLA4X/2LEs28BE8mkw/ew0gkUXosuFC3/5JB+cBG6HDzpuukOFNrOt7uFenl06jutFdoRedJ/v1wQM5c6ZueSVm3iU4+3hyaz4ZMdeg9AYfAwA4gXc1Jz7i0o+gBqUEfXcGPfVenAjPhmQiintAc0WzEmzxP4HL4fQ0ftbCFFX22Q98IZyX1j51YzNIp08eF0jhY9MWBuzT/V8acgGacrqz9YMwrJo0cWlXiZBq+Hq7f3loDqI+AdZLKiRcRra+2OEwlkScuMU7/ZC80ovBg0ItcJMOPzWvpqIaRrHGREGrNlS3aK5XgK7cqN31LuPS99sv++5zpOTwWm9G/Dx5MPXnL7pWJLCt7HBot2OF9iyjlYIIiIME+1EZdMJVoVNiE+I3HA6BT1B//unZp5J3RkwSbGA2cDh7YX0++WtWxNiqNWHK/nieLGd4c/oNXtmUEif7UGC2OxXoUsIOFOeF1UGYzo+HHWhihNs++sOAy5IEFRX85QO69w0Y1WSbk2QplJErTTx/D10yczLu0hptZH/Fv7Peg/Ic3BZ2osbbz8lTstm3zJQLJ59TqpqCXhhlnMiA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: keycloak

